// Command gencss writes the chroma stylesheet for both colour schemes.
// Run with `go generate ./internal/render/...`.
//
// Both schemes are toned from one chroma style rather than paired with a
// second one, because no style chroma ships covers another's token set:
// a class the light block styles and the dark block does not keeps its
// light colour on the dark code background, which is what left 23 tokens
// unreadable in the dark scheme (davison/md-notes#54). Generating both
// blocks from the same palette makes the two class sets equal by
// construction; each colour is then moved, hue and saturation intact,
// until it clears WCAG AA against the background it is actually drawn on.
package main

import (
	"bytes"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/alecthomas/chroma/v2"
	chromahtml "github.com/alecthomas/chroma/v2/formatters/html"
	"github.com/alecthomas/chroma/v2/styles"

	"github.com/davison/md-notes/internal/render"
)

// baseStyle is the palette both colour schemes are toned from.
const baseStyle = "github"

// minContrast is the WCAG AA contrast ratio for body text. Every colour
// the stylesheet declares clears it against the background it lands on —
// the token's own background where it has one, the scheme's code
// background otherwise.
const minContrast = 4.5

// tintTolerance is how far a token's own background may drift, in
// contrast ratio against the page it sits on, between the two schemes. A
// highlight has to stand off the page by as much in the dark scheme as in
// the light one: the dark line highlight used to be #191919 on #1b1b1b,
// a separation of 1.02 where the light one has 1.19.
const tintTolerance = 0.05

// The stylesheet is generated beside the application stylesheet it reads
// the code background out of.
const appStylesheet = "style.css"

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: gencss OUTFILE")
		os.Exit(2)
	}
	out := os.Args[1]
	app, err := os.ReadFile(filepath.Join(filepath.Dir(out), appStylesheet))
	if err != nil {
		fatal(err)
	}
	css, err := generate(app)
	if err != nil {
		fatal(err)
	}
	if err := os.WriteFile(out, css, 0o644); err != nil {
		fatal(err)
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "gencss:", err)
	os.Exit(1)
}

// generate renders the stylesheet from the application stylesheet, which
// supplies the code background of each colour scheme.
func generate(app []byte) ([]byte, error) {
	light, dark, err := codeBackgrounds(app)
	if err != nil {
		return nil, err
	}
	base, err := namedStyle(baseStyle)
	if err != nil {
		return nil, err
	}
	lightStyle, err := tone(base, light, light)
	if err != nil {
		return nil, err
	}
	darkStyle, err := tone(base, light, dark)
	if err != nil {
		return nil, err
	}
	// The prefix comes from the renderer, so the classes the highlighter
	// emits and the ones this stylesheet selects cannot drift apart.
	f := chromahtml.New(chromahtml.WithClasses(true), chromahtml.ClassPrefix(render.ClassPrefix))
	var out bytes.Buffer
	out.WriteString("/* Generated by internal/render/gencss. Do not edit. */\n")
	out.WriteString("/* Token colours only: code block backgrounds come from style.css. */\n")
	out.WriteString("/* Both schemes are toned from chroma's " + baseStyle + " palette against\n")
	out.WriteString("   that scheme's --bg, so the two blocks style the same classes and\n")
	out.WriteString("   every colour clears WCAG AA on the background it is drawn on. */\n")
	block, err := tokensOnly(css(f, lightStyle))
	if err != nil {
		return nil, err
	}
	out.Write(block)
	out.WriteString("\n@media (prefers-color-scheme: dark) {\n")
	if block, err = tokensOnly(css(f, darkStyle)); err != nil {
		return nil, err
	}
	out.Write(block)
	out.WriteString("}\n")
	if err := verify(out.Bytes(), light, dark); err != nil {
		return nil, err
	}
	return out.Bytes(), nil
}

// namedStyle resolves a chroma style by name. styles.Get substitutes its
// fallback for a name it does not know rather than reporting the miss,
// which is how the dark block came to be a style nobody chose.
func namedStyle(name string) (*chroma.Style, error) {
	s := styles.Get(name)
	if s == nil || s.Name != name {
		got := "nothing"
		if s != nil {
			got = strconv.Quote(s.Name)
		}
		return nil, fmt.Errorf("chroma has no style %q — styles.Get returned %s instead; "+
			"pick a style chroma ships or vendor the palette", name, got)
	}
	return s, nil
}

func css(f *chromahtml.Formatter, style *chroma.Style) []byte {
	var b bytes.Buffer
	if err := f.WriteCSS(&b, style); err != nil {
		panic(err)
	}
	return b.Bytes()
}

// tokensOnly drops the page and pre-wrapper background rules so the app's
// own code block styling applies in both colour schemes.
func tokensOnly(in []byte) ([]byte, error) {
	var out bytes.Buffer
	dropped := 0
	for _, line := range strings.Split(string(in), "\n") {
		if strings.HasPrefix(line, "/* Background */") || strings.HasPrefix(line, "/* PreWrapper */") {
			dropped++
			continue
		}
		if line == "" {
			continue
		}
		out.WriteString(line)
		out.WriteByte('\n')
	}
	if dropped != 2 {
		return nil, fmt.Errorf("expected to drop the Background and PreWrapper rules, dropped %d", dropped)
	}
	return out.Bytes(), nil
}

// tone rebuilds base for one colour scheme. Every token base styles gets
// an explicit entry, so the class sets of the two schemes are equal and
// nothing falls through to a colour meant for the other one.
//
// A colour keeps the emphasis it carries in the source palette: its
// target contrast is the ratio it already has against the source
// background, floored at AA, and it is moved along its own hue until it
// reaches that ratio against the destination background. Black keywords
// on white therefore become white keywords on the dark background, and
// muted comments stay muted — at AA rather than below it.
func tone(base *chroma.Style, srcBG, dstBG chroma.Colour) (*chroma.Style, error) {
	b := chroma.NewStyleBuilder(base.Name)
	// The style's own page background is subtracted, the way chroma's CSS
	// writer does, so only a token that sets a background of its own keeps
	// one: the app paints the code block.
	page := base.Get(chroma.Background)
	for _, tt := range styledTypes(base) {
		e := base.Get(tt).Sub(page)
		toned := chroma.StyleEntry{Bold: e.Bold, Italic: e.Italic, Underline: e.Underline, Border: e.Border}
		src, dst := srcBG, dstBG
		if e.Background.IsSet() {
			toned.Background = tint(e.Background, srcBG, dstBG)
			src, dst = e.Background, toned.Background
		}
		if e.Colour.IsSet() {
			target := math.Max(contrast(e.Colour, src), minContrast)
			toned.Colour = readable(e.Colour, dst, target)
		}
		b.AddEntry(tt, toned)
	}
	return b.Build()
}

// styledTypes lists the token types the formatter writes a rule for: the
// ones whose entry survives subtracting the style's background, which is
// the same test chroma's CSS writer applies.
func styledTypes(s *chroma.Style) []chroma.TokenType {
	bg := s.Get(chroma.Background)
	var out []chroma.TokenType
	for tt := range chroma.StandardTypes {
		if tt == chroma.Background || tt == chroma.PreWrapper {
			continue
		}
		if s.Get(tt).Sub(bg).IsZero() {
			continue
		}
		out = append(out, tt)
	}
	sort.Slice(out, func(i, j int) bool { return out[i] < out[j] })
	return out
}

// readable returns c moved away from bg along its own hue until it
// reaches the target contrast ratio, or the nearest extreme when the
// ratio is out of reach. A colour that already clears the target from the
// correct side of bg is returned untouched, so the light scheme changes
// only where the source palette falls below AA.
func readable(c, bg chroma.Colour, target float64) chroma.Colour {
	l := luminance(bg)
	if lightenAgainst(bg) {
		want := target*(l+0.05) - 0.05
		if luminance(c) >= want {
			return c
		}
		return toLuminance(c, want, true)
	}
	want := (l+0.05)/target - 0.05
	if luminance(c) <= want {
		return c
	}
	return toLuminance(c, want, false)
}

// tint carries a token's own background across schemes. It keeps the
// tint's separation from the page rather than its absolute lightness — a
// line highlight one step off white becomes one step off the dark
// background instead of the near-black that is invisible on it — and
// reaches the new lightness by blending the tint's hue into the
// destination background, which keeps dark tints from turning garish.
func tint(c, srcBG, dstBG chroma.Colour) chroma.Colour {
	if srcBG == dstBG {
		return c
	}
	ratio := contrast(c, srcBG)
	l := luminance(dstBG)
	var want float64
	if lightenAgainst(dstBG) {
		want = ratio*(l+0.05) - 0.05
	} else {
		want = (l+0.05)/ratio - 0.05
	}
	want = math.Min(math.Max(want, 0), 1)
	h, s, _ := toHSL(c)
	if blended, ok := blendToLuminance(dstBG, fromHSL(h, s, 0.5), want); ok {
		return blended
	}
	return toLuminance(c, want, lightenAgainst(dstBG))
}

// contrastCrossover is the relative luminance at which white and black
// contrast equally against a background: (L+0.05)^2 = 1.05*0.05.
const contrastCrossover = 0.1791

// lightenAgainst reports whether readable text on bg has to be lighter
// than it rather than darker.
func lightenAgainst(bg chroma.Colour) bool { return luminance(bg) < contrastCrossover }

// toLuminance returns c at the least lightness whose relative luminance
// is at least want, or the greatest whose luminance is at most want,
// preserving hue and saturation. Luminance rises monotonically with HSL
// lightness, so the bisection is exact to the 8-bit channel.
func toLuminance(c chroma.Colour, want float64, atLeast bool) chroma.Colour {
	h, s, _ := toHSL(c)
	ok := func(l float64) bool {
		if atLeast {
			return luminance(fromHSL(h, s, l)) >= want
		}
		return luminance(fromHSL(h, s, l)) <= want
	}
	lo, hi := 0.0, 1.0
	if atLeast {
		if !ok(hi) {
			return fromHSL(h, s, hi)
		}
		for i := 0; i < 32; i++ {
			m := (lo + hi) / 2
			if ok(m) {
				hi = m
			} else {
				lo = m
			}
		}
		return fromHSL(h, s, hi)
	}
	if !ok(lo) {
		return fromHSL(h, s, lo)
	}
	for i := 0; i < 32; i++ {
		m := (lo + hi) / 2
		if ok(m) {
			lo = m
		} else {
			hi = m
		}
	}
	return fromHSL(h, s, lo)
}

// blendToLuminance mixes over into base until the result reaches want,
// reporting false when the blend cannot get there.
func blendToLuminance(base, over chroma.Colour, want float64) (chroma.Colour, bool) {
	up := luminance(over) > luminance(base)
	ok := func(a float64) bool {
		if up {
			return luminance(mix(base, over, a)) >= want
		}
		return luminance(mix(base, over, a)) <= want
	}
	if !ok(1) {
		return 0, false
	}
	lo, hi := 0.0, 1.0
	for i := 0; i < 32; i++ {
		m := (lo + hi) / 2
		if ok(m) {
			hi = m
		} else {
			lo = m
		}
	}
	return mix(base, over, hi), true
}

func mix(a, b chroma.Colour, t float64) chroma.Colour {
	f := func(x, y uint8) uint8 {
		return uint8(math.Round(float64(x)*(1-t) + float64(y)*t))
	}
	return chroma.NewColour(f(a.Red(), b.Red()), f(a.Green(), b.Green()), f(a.Blue(), b.Blue()))
}

// luminance is the WCAG relative luminance of a colour.
func luminance(c chroma.Colour) float64 {
	f := func(v uint8) float64 {
		s := float64(v) / 255
		if s <= 0.03928 {
			return s / 12.92
		}
		return math.Pow((s+0.055)/1.055, 2.4)
	}
	return 0.2126*f(c.Red()) + 0.7152*f(c.Green()) + 0.0722*f(c.Blue())
}

// contrast is the WCAG contrast ratio between two colours, from 1 to 21.
func contrast(a, b chroma.Colour) float64 {
	x, y := luminance(a), luminance(b)
	if x < y {
		x, y = y, x
	}
	return (x + 0.05) / (y + 0.05)
}

func toHSL(c chroma.Colour) (h, s, l float64) {
	r, g, b := float64(c.Red())/255, float64(c.Green())/255, float64(c.Blue())/255
	max := math.Max(r, math.Max(g, b))
	min := math.Min(r, math.Min(g, b))
	l = (max + min) / 2
	if max == min {
		return 0, 0, l
	}
	d := max - min
	if l > 0.5 {
		s = d / (2 - max - min)
	} else {
		s = d / (max + min)
	}
	switch max {
	case r:
		h = (g - b) / d
		if g < b {
			h += 6
		}
	case g:
		h = (b-r)/d + 2
	default:
		h = (r-g)/d + 4
	}
	return h / 6, s, l
}

func fromHSL(h, s, l float64) chroma.Colour {
	if s == 0 {
		v := uint8(math.Round(l * 255))
		return chroma.NewColour(v, v, v)
	}
	var q float64
	if l < 0.5 {
		q = l * (1 + s)
	} else {
		q = l + s - l*s
	}
	p := 2*l - q
	channel := func(t float64) uint8 {
		if t < 0 {
			t++
		}
		if t > 1 {
			t--
		}
		switch {
		case t < 1.0/6:
			return uint8(math.Round((p + (q-p)*6*t) * 255))
		case t < 1.0/2:
			return uint8(math.Round(q * 255))
		case t < 2.0/3:
			return uint8(math.Round((p + (q-p)*(2.0/3-t)*6) * 255))
		default:
			return uint8(math.Round(p * 255))
		}
	}
	return chroma.NewColour(channel(h+1.0/3), channel(h), channel(h-1.0/3))
}

// bgPattern matches the --bg custom property the application stylesheet
// declares for each colour scheme; darkPattern finds where the dark one
// begins.
var (
	bgPattern   = regexp.MustCompile(`--bg:\s*(#[0-9a-fA-F]{6})\s*;`)
	darkPattern = regexp.MustCompile(`@media\s*\(\s*prefers-color-scheme:\s*dark\s*\)`)
)

// codeBackgrounds reads the code block background of each colour scheme
// out of the application stylesheet, where `.markdown pre` takes
// `var(--bg)`. Reading them keeps the contrast the generator asserts tied
// to the background the browser actually paints.
func codeBackgrounds(app []byte) (light, dark chroma.Colour, err error) {
	found := bgPattern.FindAllSubmatchIndex(app, -1)
	if len(found) != 2 {
		return 0, 0, fmt.Errorf("expected two --bg declarations in %s, found %d", appStylesheet, len(found))
	}
	at := darkPattern.FindIndex(app)
	if at == nil {
		return 0, 0, fmt.Errorf("no dark colour scheme media query in %s", appStylesheet)
	}
	if found[0][0] > at[0] || found[1][0] < at[1] {
		return 0, 0, fmt.Errorf("the two --bg declarations in %s do not straddle the dark media query", appStylesheet)
	}
	light = chroma.ParseColour(string(app[found[0][2]:found[0][3]]))
	dark = chroma.ParseColour(string(app[found[1][2]:found[1][3]]))
	if !light.IsSet() || !dark.IsSet() {
		return 0, 0, fmt.Errorf("unparsable --bg in %s", appStylesheet)
	}
	return light, dark, nil
}

// rule is one declaration block of the generated stylesheet.
type rule struct {
	colour     chroma.Colour
	background chroma.Colour
}

var (
	rulePattern   = regexp.MustCompile(`\.[a-z-]+chroma \.([a-zA-Z0-9-]+) \{([^}]*)\}`)
	colourPattern = regexp.MustCompile(`(^|[;\s])color:\s*(#[0-9a-fA-F]{6})`)
	bgColourPat   = regexp.MustCompile(`background-color:\s*(#[0-9a-fA-F]{6})`)
)

// blocks splits the generated stylesheet into its light rules and the
// rules inside the dark media query.
func blocks(css []byte) (light, dark map[string]rule) {
	text := string(css)
	cut := strings.Index(text, "@media")
	if cut < 0 {
		cut = len(text)
	}
	return parseRules(text[:cut]), parseRules(text[cut:])
}

func parseRules(text string) map[string]rule {
	out := map[string]rule{}
	for _, m := range rulePattern.FindAllStringSubmatch(text, -1) {
		r := rule{}
		if c := colourPattern.FindStringSubmatch(m[2]); c != nil {
			r.colour = chroma.ParseColour(c[2])
		}
		if c := bgColourPat.FindStringSubmatch(m[2]); c != nil {
			r.background = chroma.ParseColour(c[1])
		}
		out[m[1]] = r
	}
	return out
}

// verify is the generator's own gate: it re-reads what it is about to
// write and refuses a stylesheet where a scheme is missing a class the
// other one styles, or where a colour would land below AA on the
// background it is drawn on.
func verify(css []byte, lightBG, darkBG chroma.Colour) error {
	light, dark := blocks(css)
	if len(light) == 0 || len(dark) == 0 {
		return fmt.Errorf("generated %d light and %d dark rules", len(light), len(dark))
	}
	var problems []string
	for class := range light {
		if _, ok := dark[class]; !ok {
			problems = append(problems, fmt.Sprintf("%s is styled in the light scheme only", class))
		}
	}
	for class := range dark {
		if _, ok := light[class]; !ok {
			problems = append(problems, fmt.Sprintf("%s is styled in the dark scheme only", class))
		}
	}
	for class, l := range light {
		d, ok := dark[class]
		if !ok {
			continue
		}
		if l.background.IsSet() != d.background.IsSet() {
			problems = append(problems, fmt.Sprintf("%s has a background of its own in one scheme only", class))
			continue
		}
		if !l.background.IsSet() {
			continue
		}
		want, got := contrast(l.background, lightBG), contrast(d.background, darkBG)
		if math.Abs(want-got) > tintTolerance {
			problems = append(problems, fmt.Sprintf(
				"%s stands %.3f:1 off the dark page and %.3f:1 off the light one", class, got, want))
		}
	}
	for _, scheme := range []struct {
		name  string
		bg    chroma.Colour
		rules map[string]rule
	}{{"light", lightBG, light}, {"dark", darkBG, dark}} {
		for class, r := range scheme.rules {
			bg := scheme.bg
			if r.background.IsSet() {
				bg = r.background
			}
			if !r.colour.IsSet() {
				continue
			}
			if got := contrast(r.colour, bg); got < minContrast {
				problems = append(problems, fmt.Sprintf("%s scheme: %s is %s on %s, %.2f:1",
					scheme.name, class, r.colour, bg, got))
			}
		}
	}
	if len(problems) > 0 {
		sort.Strings(problems)
		return fmt.Errorf("stylesheet fails its own checks:\n  %s", strings.Join(problems, "\n  "))
	}
	return nil
}
