// Command gencss writes the chroma stylesheet for both colour schemes.
// Run with `go generate ./internal/render/...`.
package main

import (
	"bytes"
	"fmt"
	"os"
	"strings"

	chromahtml "github.com/alecthomas/chroma/v2/formatters/html"
	"github.com/alecthomas/chroma/v2/styles"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: gencss OUTFILE")
		os.Exit(2)
	}
	f := chromahtml.New(chromahtml.WithClasses(true))
	var out bytes.Buffer
	out.WriteString("/* Generated by internal/render/gencss. Do not edit. */\n")
	out.WriteString("/* Token colours only: code block backgrounds come from style.css. */\n")
	out.Write(tokensOnly(css(f, "github")))
	out.WriteString("\n@media (prefers-color-scheme: dark) {\n")
	out.Write(tokensOnly(css(f, "github-dark")))
	out.WriteString("}\n")
	if err := os.WriteFile(os.Args[1], out.Bytes(), 0o644); err != nil {
		panic(err)
	}
}

func css(f *chromahtml.Formatter, style string) []byte {
	var b bytes.Buffer
	if err := f.WriteCSS(&b, styles.Get(style)); err != nil {
		panic(err)
	}
	return b.Bytes()
}

// tokensOnly drops the page and pre-wrapper background rules so the app's
// own code block styling applies in both colour schemes.
func tokensOnly(in []byte) []byte {
	var out bytes.Buffer
	for _, line := range strings.Split(string(in), "\n") {
		if strings.HasPrefix(line, "/* Background */") || strings.HasPrefix(line, "/* PreWrapper */") {
			continue
		}
		if line == "" {
			continue
		}
		out.WriteString(line)
		out.WriteByte('\n')
	}
	return out.Bytes()
}
