// Command gencss writes the chroma stylesheet for both colour schemes.
// Run with `go generate ./internal/render/...`.
package main

import (
	"bytes"
	"fmt"
	"os"

	chromahtml "github.com/alecthomas/chroma/v2/formatters/html"
	"github.com/alecthomas/chroma/v2/styles"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: gencss OUTFILE")
		os.Exit(2)
	}
	f := chromahtml.New(chromahtml.WithClasses(true))
	var out bytes.Buffer
	out.WriteString("/* Generated by internal/render/gencss. Do not edit. */\n")
	if err := f.WriteCSS(&out, styles.Get("github")); err != nil {
		panic(err)
	}
	var dark bytes.Buffer
	if err := f.WriteCSS(&dark, styles.Get("github-dark")); err != nil {
		panic(err)
	}
	out.WriteString("\n@media (prefers-color-scheme: dark) {\n")
	out.Write(dark.Bytes())
	out.WriteString("}\n")
	if err := os.WriteFile(os.Args[1], out.Bytes(), 0o644); err != nil {
		panic(err)
	}
}
