// Command genmetrics writes the advance-width table the diagram package
// measures label text with. Run with `go generate ./internal/diagram/...`.
//
// A diagram is drawn on the server and shown as an image, so the daemon has
// to know how wide a label will be in a browser it never sees. The table is
// the advance widths of Noto Sans Regular, read out of the font file named
// on the command line: of the sans-serif faces a reader's browser is likely
// to fall back to it is among the widest (Roboto, Arial and Helvetica all
// set narrower), so a box sized by it holds its label in any of them. The
// SVG writer names Noto Sans first in its font-family for the same reason.
//
// Only the widths are taken — one number per character, in thousandths of
// an em — not glyph outlines or any other part of the font, and the ranges
// are the ones a flowchart label in a Latin, Greek or Cyrillic script uses.
// Everything else is estimated by the package itself (see width.go).
//
// The font is parsed here rather than through golang.org/x/image so that a
// generator run by hand does not add a module to the daemon's graph: the
// three tables it needs (head, hhea and hmtx, plus a format 4 cmap) are a
// few dozen lines to read.
package main

import (
	"bytes"
	"encoding/binary"
	"errors"
	"fmt"
	"go/format"
	"os"
)

// ranges are the code points the table covers, inclusive.
var ranges = [][2]rune{
	{0x0020, 0x024F}, // Basic Latin through Latin Extended-B
	{0x0370, 0x03FF}, // Greek
	{0x0400, 0x04FF}, // Cyrillic
	{0x2010, 0x205F}, // General Punctuation: dashes, quotes, bullets, ellipsis
	{0x20A0, 0x20BF}, // Currency symbols
	{0x2190, 0x21FF}, // Arrows
}

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: genmetrics NotoSans-Regular.ttf out.go")
		os.Exit(2)
	}
	src, err := os.ReadFile(os.Args[1])
	if err != nil {
		fail(err)
	}
	f, err := parse(src)
	if err != nil {
		fail(err)
	}
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by genmetrics from %s; DO NOT EDIT.\n\n", f.name)
	b.WriteString("package diagram\n\n")
	b.WriteString("// advanceSegments are Noto Sans Regular's advance widths, in thousandths\n// of an em, for the code points each segment starts at.\n")
	b.WriteString("var advanceSegments = []advanceSegment{\n")
	for _, r := range ranges {
		fmt.Fprintf(&b, "{first: 0x%04X, widths: []uint16{", r[0])
		for c := r[0]; c <= r[1]; c++ {
			w := 0
			if g, ok := f.glyph(c); ok {
				w = f.advance(g)
			}
			fmt.Fprintf(&b, "%d,", w)
		}
		b.WriteString("}},\n")
	}
	b.WriteString("}\n")
	out, err := format.Source(b.Bytes())
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile(os.Args[2], out, 0o644); err != nil {
		fail(err)
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "genmetrics:", err)
	os.Exit(1)
}

type font struct {
	name       string
	unitsPerEm int
	hmetrics   []uint16 // advance widths, numberOfHMetrics long
	cmap       map[rune]uint16
}

// advance is a glyph's advance width scaled to thousandths of an em. A
// glyph past the end of hmtx's long metrics takes the last one's width, as
// the format specifies.
func (f *font) advance(g uint16) int {
	i := int(g)
	if i >= len(f.hmetrics) {
		i = len(f.hmetrics) - 1
	}
	return (int(f.hmetrics[i])*1000 + f.unitsPerEm/2) / f.unitsPerEm
}

func (f *font) glyph(r rune) (uint16, bool) {
	g, ok := f.cmap[r]
	return g, ok && g != 0
}

// parse reads the tables the generator needs. It trusts the offsets a
// font gives it no further than the slice bounds: a truncated or corrupt
// file is reported as one, not a crash.
func parse(b []byte) (f *font, err error) {
	defer func() {
		if r := recover(); r != nil {
			f, err = nil, fmt.Errorf("malformed font: %v", r)
		}
	}()
	if len(b) < 12 {
		return nil, errors.New("too short to be a font")
	}
	n := int(binary.BigEndian.Uint16(b[4:]))
	tables := map[string][]byte{}
	for i := 0; i < n; i++ {
		rec := b[12+16*i:]
		tag := string(rec[:4])
		off := binary.BigEndian.Uint32(rec[8:])
		ln := binary.BigEndian.Uint32(rec[12:])
		if int(off)+int(ln) > len(b) {
			return nil, fmt.Errorf("table %s runs past the end of the file", tag)
		}
		tables[tag] = b[off : off+ln]
	}
	for _, t := range []string{"head", "hhea", "hmtx", "cmap", "name"} {
		if tables[t] == nil {
			return nil, fmt.Errorf("no %s table", t)
		}
	}
	f = &font{
		unitsPerEm: int(binary.BigEndian.Uint16(tables["head"][18:])),
		cmap:       map[rune]uint16{},
		name:       fullName(tables["name"]),
	}
	nh := int(binary.BigEndian.Uint16(tables["hhea"][34:]))
	for i := 0; i < nh; i++ {
		f.hmetrics = append(f.hmetrics, binary.BigEndian.Uint16(tables["hmtx"][4*i:]))
	}
	if err := readCmap(tables["cmap"], f.cmap); err != nil {
		return nil, err
	}
	return f, nil
}

// readCmap reads the Unicode BMP subtable (platform 3, encoding 1, format 4).
func readCmap(t []byte, m map[rune]uint16) error {
	n := int(binary.BigEndian.Uint16(t[2:]))
	for i := 0; i < n; i++ {
		rec := t[4+8*i:]
		platform, encoding := binary.BigEndian.Uint16(rec), binary.BigEndian.Uint16(rec[2:])
		sub := t[binary.BigEndian.Uint32(rec[4:]):]
		if platform != 3 || encoding != 1 || binary.BigEndian.Uint16(sub) != 4 {
			continue
		}
		segs := int(binary.BigEndian.Uint16(sub[6:])) / 2
		ends := sub[14:]
		starts := ends[2*segs+2:]
		deltas := starts[2*segs:]
		offsets := deltas[2*segs:]
		for s := 0; s < segs; s++ {
			end := rune(binary.BigEndian.Uint16(ends[2*s:]))
			start := rune(binary.BigEndian.Uint16(starts[2*s:]))
			delta := binary.BigEndian.Uint16(deltas[2*s:])
			ro := int(binary.BigEndian.Uint16(offsets[2*s:]))
			for c := start; c <= end && c != 0xFFFF; c++ {
				var g uint16
				if ro == 0 {
					g = uint16(c) + delta
				} else {
					at := 2*s + ro + 2*int(c-start)
					g = binary.BigEndian.Uint16(offsets[at:])
					if g != 0 {
						g += delta
					}
				}
				m[c] = g
			}
		}
		return nil
	}
	return errors.New("no Unicode BMP (3,1,4) cmap subtable")
}

// fullName is the font's full name and version (name IDs 4 and 5) from its
// Windows Unicode records, for the generated file's header.
func fullName(t []byte) string {
	n := int(binary.BigEndian.Uint16(t[2:]))
	strs := t[binary.BigEndian.Uint16(t[4:]):]
	get := func(id uint16) string {
		for i := 0; i < n; i++ {
			rec := t[6+12*i:]
			if binary.BigEndian.Uint16(rec) != 3 || binary.BigEndian.Uint16(rec[6:]) != id {
				continue
			}
			ln := binary.BigEndian.Uint16(rec[8:])
			off := binary.BigEndian.Uint16(rec[10:])
			u := strs[off : off+ln]
			r := make([]rune, 0, len(u)/2)
			for j := 0; j+1 < len(u); j += 2 {
				r = append(r, rune(binary.BigEndian.Uint16(u[j:])))
			}
			return string(r)
		}
		return "?"
	}
	return get(4) + " (" + get(5) + ")"
}
