package diagram

import (
	"strings"
	"unicode"
)

// Text is measured against Noto Sans Regular's advance widths (metrics.go,
// generated by genmetrics), because the daemon cannot ask the reader's
// browser how wide a label will be. The SVG names Noto Sans first in its
// font-family; the faces after it are narrower, so a box sized here holds
// its text in any of them.

type advanceSegment struct {
	first  rune
	widths []uint16
}

const (
	fontSize   = 14.0
	lineHeight = 1.3 * fontSize
	// capHeight is Noto Sans's cap height in ems: a line's baseline sits
	// half a cap height below its centre, which centres the capitals.
	capHeight = 0.714
	// wrapWidth is where a label's line is broken at a space, as mermaid's
	// own labels are.
	wrapWidth = 200.0
	// widthSlack allows for a renderer's rounding and kerning.
	widthSlack = 1.04
)

// advance is a character's width in thousandths of an em.
func advance(r rune) int {
	for _, s := range advanceSegments {
		if r >= s.first && int(r-s.first) < len(s.widths) {
			if w := s.widths[r-s.first]; w > 0 {
				return int(w)
			}
			break
		}
	}
	switch {
	case unicode.Is(unicode.Mn, r) || unicode.Is(unicode.Me, r) || unicode.Is(unicode.Cf, r):
		return 0
	case wide(r):
		return 1000
	}
	return 700
}

// wide reports the East Asian wide and fullwidth ranges, and emoji, which
// take a full em in any face.
func wide(r rune) bool {
	return r >= 0x1100 && r <= 0x115F ||
		r >= 0x2E80 && r <= 0xA4CF ||
		r >= 0xAC00 && r <= 0xD7A3 ||
		r >= 0xF900 && r <= 0xFAFF ||
		r >= 0xFE30 && r <= 0xFE4F ||
		r >= 0xFF00 && r <= 0xFF60 ||
		r >= 0xFFE0 && r <= 0xFFE6 ||
		r >= 0x1F000 && r <= 0x1FAFF ||
		r >= 0x20000 && r <= 0x3FFFD
}

// textWidth is a line's width in pixels at the diagram's font size.
func textWidth(s string) float64 {
	total := 0
	for _, r := range s {
		total += advance(r)
	}
	return float64(total) / 1000 * fontSize * widthSlack
}

// wrap breaks each line of a label at spaces so none is wider than
// wrapWidth, unless a single word is.
func wrap(lines []string) []string {
	var out []string
	for _, l := range lines {
		words := strings.Fields(l)
		if len(words) == 0 {
			out = append(out, "")
			continue
		}
		cur := words[0]
		for _, w := range words[1:] {
			if textWidth(cur+" "+w) > wrapWidth {
				out = append(out, cur)
				cur = w
				continue
			}
			cur += " " + w
		}
		out = append(out, cur)
	}
	return out
}

// textBox is the size of a block of lines.
func textBox(lines []string) (w, h float64) {
	for _, l := range lines {
		if tw := textWidth(l); tw > w {
			w = tw
		}
	}
	return w, float64(len(lines)) * lineHeight
}
